baseURL: "https://www.rasche.dev"
title: Tjark Rasche
paginate: 10
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: rasche.dev
  description: "ExampleSite description"
  author: Me
  # author: ["Me", "You"] # multiple authors

  images: ["<link or path of image for opengraph, twitter-cards>"]

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]


  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Tjark Rasche
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/TjarkRasche"
    - name: github
      url: "https://github.com/tjrasche"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

menu:
  main:
    - identifier: Categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: Tagd
      name: tags
      url: /tags/
      weight: 20
outputs:
  home:
    - HTML
    - RSS
    - JSON